### ISSUE TITLE
I am receiving an error when attempting to post a job to the board

### ISSUE THREAD

**Issue by davekenn4242** [code4lib/job_board#51]
I received the following error when attempting to post a job to the job board:

We're sorry but something went wrong.
If you are the application owner check the logs for more information.

This occurred yesterday as well as 3 hours ago today.

**Comment by cbeer** [comment]
Thanks; it looks like it ran out of disk space. Try again now.

**Comment by davekenn4242** [comment]
Thank you.  It worked
